### PR TITLE
Add `MultipleNegativesSymmetricRankingLoss` to package reference for losses.

### PR DESCRIPTION
**Pull request by PhilipMay**
Add `MultipleNegativesSymmetricRankingLoss` to package reference for losses.

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hello!

Agreed to this - I think after this PR, only https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/losses/ContrastiveTensionLoss.py is missing. 

- Tom Aarsen

**Comment by PhilipMay** [comment]
What about this MR? It is kind of stuck... 
@tomaarsen could you help?

**Comment by tomaarsen** [comment]
Definitely! My focus is on SetFit for now, until I get the next release out there, and then I will shift focus on Sentence Transformers and start tackling open PRs and issues! Sit tight :) 

- Tom Aarsen

**Comment by PhilipMay** [comment]
@tomaarsen by the way: as far as I can see the Sphinx Build is not automated as a GH Action.
Should that be changed?

**Comment by tomaarsen** [comment]
I'd love to change it, but I have to discuss with Nils how he normally builds and deploys the docs. I don't have access to that yet, I don't think. I'll meet him on Monday to talk about it.

- Tom Aarsen

**Comment by PhilipMay** [comment]
Ohh ok. Please give him my best regards.
If you want I can do a PR for the Sphinx GH Action.
Should I create a "Feature Request"?

**Comment by tomaarsen** [comment]
That would definitely be useful, but I have to say that I don't know where the built docs would even go. My other projects would automatically push the docs to `gh-pages`, but that's not being used here it seems. I also can't find another repository that has the docs in it or something. I'll just ask @nreimers first.

- Tom Aarsen

**Pull request merged**
