### PR TITLE
Fix cross encoder device issue

### LINKED ISSUE #3078: `CrossEncoder` is not pushed to cuda until predict is called, even if cuda is specified as device.
Hi, this is more like a question rather than a bug or issue.

When I specify the target device during initialization of any CrossEncoder, the model is not pushed to that device until the `predict` or the `fit` method is called, until then the model is kept in cpu.

```python
from sentence_transformers import CrossEncoder

model2 = CrossEncoder("mixedbread-ai/mxbai-rerank-large-v1", device="cuda:0")
print(model2.model.device)
# cpu
```

I mean I expect the model to be pushed to the specified device during initialization and until I am calling predict it is taking up my system Ram.
Is there any high level reason(s) why this is the case?

### PR DESCRIPTION
**Pull request by susnato**
Fixes #3078

- fixed the previous issue and now the model is pushed to the specified device when the object is created.
- added new method `to` which directly pushes the model to the specified device, removing the need to use model.model.to
- added 2 tests to make sure it works as expected

### CODE REVIEW

**Comment by susnato** [comment]
cc: @tomaarsen

**Comment by tomaarsen** [comment]
Hello!

Well done here @susnato! I made some tiny adjustments, primarily surrounding the removal of `_target_device`. Despite it being a "private attribute", I imagine that some users updated `model._target_device` to move the model from devices, so I've added a property + setter to ensure that it's still possible (although it's not recommended).
We have something similar for the `SentenceTransformer` class.

What do you think? Oh, I'm also going to try the Copilot reviewer on this.

- Tom Aarsen

**Review by tomaarsen — APPROVED** [review]

**Comment by susnato** [comment]
hi @tomaarsen , seems good to me to have the _target_device. 

>  I'm also going to try the Copilot reviewer on this.

lol, I didn't knew this even existed!

**Comment by tomaarsen** [comment]
> lol, I didn't knew this even existed!

It's very new! I only got access a few days ago, and this is the second time that I've used it. Seems like it didn't help much this time, haha.

I'll merge this now as I think we're good to go. Thanks for the help!

- Tom Aarsen

**Pull request merged**
