### PR TITLE
Added ORT/onnx support for loading models

### PR DESCRIPTION
**Pull request by varunneal**
You can read about Optimum inference here: https://huggingface.co/docs/optimum/v1.2.1/en/onnxruntime/modeling_ort

This change is only a couple lines and will allow sentence-transformers to load models in a .onnx format.

### CODE REVIEW

**Comment by VarunNSrivastava** [comment]
Remark: you can test this PR against an existing onnx model, for example [optimum/all-MiniLM-L6-v2](https://huggingface.co/optimum/all-MiniLM-L6-v2).

**Comment by gustavz** [comment]
Hey @tomaarsen this would be a simple but great addition for anyone using ONNX quantized embeddings.
Please take it into consideration!

**Comment by gustavz** [comment]
ping @tomaarsen any chance we can get this in?

**Comment by tomaarsen** [comment]
I've added ONNX support in the latest release: https://github.com/UKPLab/sentence-transformers/releases/tag/v3.2.0 by going in the direction of #2712.

Thanks for this PR, though, it helped notify me that there's a need for this feature.

- Tom Aarsen

**Pull request closed without merging**
