### PR TITLE
Allow passing 'precision' when using 'encode_multi_process' to SentenceTransformer

### PR DESCRIPTION
**Pull request by ariel-talent-fabric**
### Overview
When using the current implementation of 'encode_multi_process' we are forced to use only the default precision, forcing us to leverage multi-process GPU capabilities.

### Details
This PR should fix this and allow setting the precision with multi-process capabilities by supporting the `precision` property when calling the `encode_multi_process` function.

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hello!

This looks solid, thanks for this! Could you please run `make style` or `pre-commit run --all` to solve the formatting issue?

- Tom Aarsen

**Comment by ariel-talent-fabric** [comment]
> Hello!
> 
> This looks solid, thanks for this! Could you please run `make style` or `pre-commit run --all` to solve the formatting issue?
> 
> * Tom Aarsen

**Comment by ariel-talent-fabric** [comment]
Done

**Comment by tomaarsen** [comment]
Excellent, thanks a bunch for this! I appreciate it.

- Tom Aarsen

**Pull request merged**
