### PR TITLE
Added method sentence_transformers.SentenceTransformer.embed(List[int]) that takes pre-encoded text from ex. transformers.BertTokenizer

### PR DESCRIPTION
**Pull request by rjurney**
This PR is not ready! I have to factor out redundant code. I want you to see it to find out if you'll accept it and what the `embed(List[int])` method name should be :)

### CODE REVIEW

**Comment by nreimers** [comment]
The PR sounds interesting.

I am currently on vacation until end of June. I will then have a look and integrate it.

**Comment by rjurney** [comment]
@nreimers thanks, I'll factor out redundant code then.

**Comment by nreimers** [comment]
Thanks for the PR.

I included the function in the encode function:
```
tokenized_sentences = [model.tokenize("my first sentence"), model.tokenize("my second sentence")]
model.encode(tokenized_sentences, is_pretokenized=True)
```

**Comment by rjurney** [comment]
@nreimers I’m assuming you factored out the duplicated code? It came down to a 3-4 line change the rest could be removed.

**Comment by nreimers** [comment]
Hi @rjurney 
Yes, I slightly changed the encode function so that it first tokenizes all text before it generates the batches. With this change, you just need a flag if the input is already tokenized or not.

**Pull request closed without merging**
