### PR TITLE
Fix syntax warning (issue #2687)

### PR DESCRIPTION
**Pull request by wyattscarpenter**
This pull request closes all of the SyntaxWarnings I noted in issue #2687. There may be more, but at least this takes care of many of them!

### CODE REVIEW

**Comment by wyattscarpenter** [comment]
Update: I ran `uv run ruff check --select W605  . --no-respect-gitignore` on the venv folder i have a copy of the project in and it seems like these are maybe the only such errors.

**Comment by ruckc** [comment]
@tomaarsen - I just tested this... can you merge?

**Review by tomaarsen — APPROVED** [review]
LGTM! Apologies that I didn't get around to this sooner myself.
Thanks for the PR!

- Tom Aarsen

**Comment by tomaarsen** [comment]
Hello!

This is fixed in v3.1.0 onwards.

- Tom Aarsen

**Pull request merged**
