### PR TITLE
Fix to issue #1760

### PR DESCRIPTION
**Pull request by iampushpdeep**
Fix to issue #1760

### CODE REVIEW

**Comment by dbuades** [comment]
I can confirm that this PR fixes the issue.

**Comment by davidbetancur8** [comment]
any updates on this?

**Comment by Jakobhenningjensen** [comment]
Any updates on when this will be merged?

**Comment by andersonbcdefg** [comment]
Hey, still need this fix please!!!!

**Comment by tomaarsen** [comment]
Hello!

#2376 has resolved this issue, while preserving backwards compatibility. It will be released in the next Sentence Transformers 2.3.0 release. Thanks for pointing me to this problem via this PR!

- Tom Aarsen

**Pull request closed without merging**
