### PR TITLE
Add support for pytorch model quantization, add quantization example

### PR DESCRIPTION
**Pull request by cdpierse**
Hi,

I recently had the need to squeeze out as much performance at inference from a sentence transformers model as possible so I had a look at integrating Pytorch's very neat quantization tools into the package.

It turned out to be a very simple change to make and I thought I would propose it as a PR to the base `SentenceTransformer` class as I had noticed there had been a mention of it recently #627. This implementation uses dynamic quantization from [Pytorch's quantization API](https://pytorch.org/docs/1.7.1/quantization.html). It specifically quantizes all `Linear` and `Embedding` modules in the Transformer model, if GPT2 like model architectures were ever added to the package we could also add `Conv1D` modules to this quantization as GPT2 uses these layers also. 

Additionally, I've added a script in the `examples/evaluation` directory to allow easy comparision of quantized versus non-quantized models, the script runs the STSBenchmark on both models (`paraphrase-distilroberta-base-v1` by default) and then runs an inference speed benchmark. I've copied the results from my machine below, as you can see the quantized model still performs fairly well on most metrics often dropping less than 1% on scores. The most notable drop occur in `Dot-Product-Similarity`. 

I think this could be a nice overall addition to the package and there are definitely some great benefits in terms of inference speed for production situations like my own. 

**STS Benchmark Results**
```
2021-02-24 21:53:38 - Use pytorch device: cpu
2021-02-24 21:53:39 - Starting regular model evaluation
2021-02-24 21:53:39 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-02-24 21:54:25 - Cosine-Similarity :       Pearson: 0.8236 Spearman: 0.8179
2021-02-24 21:54:25 - Manhattan-Distance:       Pearson: 0.7481 Spearman: 0.7478
2021-02-24 21:54:25 - Euclidean-Distance:       Pearson: 0.7518 Spearman: 0.7519
2021-02-24 21:54:25 - Dot-Product-Similarity:   Pearson: 0.7443 Spearman: 0.7356
2021-02-24 21:54:25 - Starting quantized model evaluation
2021-02-24 21:54:25 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-02-24 21:54:38 - Cosine-Similarity :       Pearson: 0.8112 Spearman: 0.8106
2021-02-24 21:54:38 - Manhattan-Distance:       Pearson: 0.7339 Spearman: 0.7315
2021-02-24 21:54:38 - Euclidean-Distance:       Pearson: 0.7392 Spearman: 0.7369
2021-02-24 21:54:38 - Dot-Product-Similarity:   Pearson: 0.7042 Spearman: 0.6861
```
**Inference Speed Report** 
Each model is run for 500 inferences on a batch of 3 short sentences. These results show ~3x improvement on inference time for this particular model. `distilroberta` is as normal while `q_distilroberta` has it's Linear and Embedding layers quantized. 
```
╒═════════════════╤═══════════╤════════╤═════════╤════════════════╤══════════════╤══════════════╤═══════════╤════════════╤══════════════╤═══════════╤════════════╤════════════╕
│ Model           │   Success │   Fail │    Took │   Infer(p/sec) │   MaxRun(ms) │   MinRun(ms) │   Std(ms) │   Mean(ms) │   Median(ms) │   IQR(ms) │   Cores(L) │   Cores(P) │
╞═════════════════╪═══════════╪════════╪═════════╪════════════════╪══════════════╪══════════════╪═══════════╪════════════╪══════════════╪═══════════╪════════════╪════════════╡
│ distilroberta   │       500 │      0 │ 17.1329 │          29.18 │         42.9 │         29.6 │    2.3832 │     34.266 │           34 │       2.9 │         16 │          8 │
├─────────────────┼───────────┼────────┼─────────┼────────────────┼──────────────┼──────────────┼───────────┼────────────┼──────────────┼───────────┼────────────┼────────────┤
│ q_distilroberta │       500 │      0 │ 5.70767 │           87.6 │         16.6 │          7.8 │   1.77495 │    11.4148 │         11.1 │       2.6 │         16 │          8 │
╘═════════════════╧═══════════╧════════╧═════════╧════════════════╧══════════════╧══════════════╧═══════════╧════════════╧══════════════╧═══════════╧════════════╧════════════╛

```

### CODE REVIEW

**Comment by nreimers** [comment]
This looks really promising. I will also test it and merge it.

Do you know if it will also lead to a speed-up on a GPU?

**Comment by cdpierse** [comment]
As of right now dynamic quantization is only supported for CPU inference, although I think GPU quantization is an area of active research at Pytorch. I have a check in place before applying quantization that makes sure the current device is `cpu` so it should just pass over silently if a user enables quantization but is making use of a GPU. 

Thankfully I think the greatest benefits of quantization come in situations where models' are on CPU's and can't benefit from GPU acceleration.

**Comment by pommedeterresautee** [comment]
Tensorrt through onnx runtime for instance provides quantization for gpu. It's supposed to bring great benefit but is quite hard to use.

**Comment by cdpierse** [comment]
Strange, I didn't realize quantization performance increase would be so reliant on the metal it's running on. Could I ask what machine you are working on ? I'm thinking it might work better with certain architectures, I'm on a Macbook Pro with a `2.3 GHz 8-Core Intel Core i9` CPU.

I ran your test and got a 3.2X speed up again. I've pasted the output below. 

```
▶ python examples/training/distillation/model_quantization.py 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 392k/392k [00:00<00:00, 1.09MB/s]
2021-03-02 09:30:59 - Load pretrained SentenceTransformer: paraphrase-distilroberta-base-v1
2021-03-02 09:30:59 - Did not find folder paraphrase-distilroberta-base-v1
2021-03-02 09:30:59 - Search model on server: http://sbert.net/models/paraphrase-distilroberta-base-v1.zip
2021-03-02 09:30:59 - Load SentenceTransformer from folder: /Users/charlesp/.cache/torch/sentence_transformers/sbert.net_models_paraphrase-distilroberta-base-v1
2021-03-02 09:31:01 - Read STSbenchmark dataset
2021-03-02 09:31:01 - Evaluating speed of unquantized model
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [02:46<00:00,  1.88it/s]
2021-03-02 09:33:47 - Done after 166.21 sec. 60.17 sentences / sec
2021-03-02 09:33:47 - Evaluating speed of quantized model
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [00:51<00:00,  6.09it/s]
2021-03-02 09:34:39 - Done after 51.50 sec. 194.16 sentences / sec
2021-03-02 09:34:39 - Speed-up: 3.23
2021-03-02 09:34:39 - Evaluate regular model
2021-03-02 09:34:39 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-02 09:35:20 - Cosine-Similarity :       Pearson: 0.8236 Spearman: 0.8179
2021-03-02 09:35:20 - Manhattan-Distance:       Pearson: 0.7481 Spearman: 0.7478
2021-03-02 09:35:20 - Euclidean-Distance:       Pearson: 0.7518 Spearman: 0.7519
2021-03-02 09:35:20 - Dot-Product-Similarity:   Pearson: 0.7443 Spearman: 0.7356



2021-03-02 09:35:20 - Evaluate quantized model
2021-03-02 09:35:20 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-02 09:35:32 - Cosine-Similarity :       Pearson: 0.8112 Spearman: 0.8106
2021-03-02 09:35:32 - Manhattan-Distance:       Pearson: 0.7339 Spearman: 0.7315
2021-03-02 09:35:32 - Euclidean-Distance:       Pearson: 0.7392 Spearman: 0.7369
2021-03-02 09:35:32 - Dot-Product-Similarity:   Pearson: 0.7042 Spearman: 0.6861
```

**Comment by nreimers** [comment]
That is interesting.

My Laptop: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz with Windows
On the server: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz with Ubuntu 20.04
	
```
2021-03-01 22:19:55 - Evaluating speed of unquantized model
2021-03-01 22:20:42 - Done after 47.01 sec. 212.71 sentences / sec
2021-03-01 22:20:42 - Evaluating speed of quantized model
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [00:37<00:00,  8.35it/s]
2021-03-01 22:21:19 - Done after 37.58 sec. 266.10 sentences / sec
2021-03-01 22:21:19 - Speed-up: 1.25
2021-03-01 22:21:19 - Evaluate regular model
2021-03-01 22:21:19 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-01 22:21:32 - Cosine-Similarity :       Pearson: 0.8236 Spearman: 0.8179
2021-03-01 22:21:32 - Manhattan-Distance:       Pearson: 0.7481 Spearman: 0.7478
2021-03-01 22:21:32 - Euclidean-Distance:       Pearson: 0.7518 Spearman: 0.7519
2021-03-01 22:21:32 - Dot-Product-Similarity:   Pearson: 0.7443 Spearman: 0.7356



2021-03-01 22:21:32 - Evaluate quantized model
2021-03-01 22:21:32 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-01 22:21:44 - Cosine-Similarity :       Pearson: 0.8095 Spearman: 0.8084
2021-03-01 22:21:44 - Manhattan-Distance:       Pearson: 0.7307 Spearman: 0.7284
2021-03-01 22:21:44 - Euclidean-Distance:       Pearson: 0.7365 Spearman: 0.7346
2021-03-01 22:21:44 - Dot-Product-Similarity:   Pearson: 0.7013 Spearman: 0.6839
```` 


On my desktop PC:   Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz with Ubuntu 16.04
```
2021-03-02 10:47:42 - Evaluating speed of unquantized model
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [01:03<00:00,  2.27it/s]
2021-03-02 10:48:46 - Done after 64.06 sec. 156.09 sentences / sec
2021-03-02 10:48:46 - Evaluating speed of quantized model
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [00:58<00:00,  2.36it/s]
2021-03-02 10:49:45 - Done after 58.58 sec. 170.71 sentences / sec
2021-03-02 10:49:45 - Speed-up: 1.09
2021-03-02 10:49:45 - Evaluate regular model
2021-03-02 10:49:45 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-02 10:50:00 - Cosine-Similarity :       Pearson: 0.8236 Spearman: 0.8179
2021-03-02 10:50:00 - Manhattan-Distance:       Pearson: 0.7481 Spearman: 0.7478
2021-03-02 10:50:00 - Euclidean-Distance:       Pearson: 0.7518 Spearman: 0.7519
2021-03-02 10:50:00 - Dot-Product-Similarity:   Pearson: 0.7443 Spearman: 0.7356



2021-03-02 10:50:00 - Evaluate quantized model
2021-03-02 10:50:00 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-02 10:50:15 - Cosine-Similarity :       Pearson: 0.8115 Spearman: 0.8090
2021-03-02 10:50:15 - Manhattan-Distance:       Pearson: 0.7366 Spearman: 0.7332
2021-03-02 10:50:15 - Euclidean-Distance:       Pearson: 0.7403 Spearman: 0.7376
2021-03-02 10:50:15 - Dot-Product-Similarity:   Pearson: 0.7025 Spearman: 0.6855
```

**Comment by cdpierse** [comment]
Yeah it is. It appears my machine is far slower than yours when it comes to unquantized evaluation and then catches up with quantization applied. 

I ran the test again this time with the number of threads not limited to 4 and got a 4x improvement. It also appears that the 3x to 4x improvement is more inline with what [Pytorch expect](https://pytorch.org/docs/stable/quantization.html#introduction-to-quantization) 

>  PyTorch supports INT8 quantization compared to typical FP32 models allowing for a 4x reduction in the model size and a 4x reduction in memory bandwidth requirements. Hardware support for INT8 computations is typically 2 to 4 times faster compared to FP32 compute. 


The only intuition I'd have here is that the floating point precision is different from the get go for both our models. Maybe it's on OS thing, or maybe you have a version of the model cached locally that is already optimized. I'm not really sure, but this is interesting so I'd like to figure it out. 

```
▶ python examples/training/distillation/model_quantization.py
2021-03-02 09:57:18 - Load pretrained SentenceTransformer: paraphrase-distilroberta-base-v1
2021-03-02 09:57:18 - Did not find folder paraphrase-distilroberta-base-v1
2021-03-02 09:57:18 - Search model on server: http://sbert.net/models/paraphrase-distilroberta-base-v1.zip
2021-03-02 09:57:18 - Load SentenceTransformer from folder: /Users/charlesp/.cache/torch/sentence_transformers/sbert.net_models_paraphrase-distilroberta-base-v1
2021-03-02 09:57:20 - Read STSbenchmark dataset
2021-03-02 09:57:20 - Evaluating speed of unquantized model
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [02:53<00:00,  1.81it/s]
2021-03-02 10:00:13 - Done after 173.09 sec. 57.77 sentences / sec
2021-03-02 10:00:13 - Evaluating speed of quantized model
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [00:42<00:00,  7.40it/s]
2021-03-02 10:00:55 - Done after 42.35 sec. 236.14 sentences / sec
2021-03-02 10:00:55 - Speed-up: 4.09
2021-03-02 10:00:55 - Evaluate regular model
2021-03-02 10:00:55 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-02 10:01:37 - Cosine-Similarity :       Pearson: 0.8236 Spearman: 0.8179
2021-03-02 10:01:37 - Manhattan-Distance:       Pearson: 0.7481 Spearman: 0.7478
2021-03-02 10:01:37 - Euclidean-Distance:       Pearson: 0.7518 Spearman: 0.7519
2021-03-02 10:01:37 - Dot-Product-Similarity:   Pearson: 0.7443 Spearman: 0.7356



2021-03-02 10:01:37 - Evaluate quantized model
2021-03-02 10:01:37 - EmbeddingSimilarityEvaluator: Evaluating the model on sts-test dataset:
2021-03-02 10:01:48 - Cosine-Similarity :       Pearson: 0.8112 Spearman: 0.8106
2021-03-02 10:01:48 - Manhattan-Distance:       Pearson: 0.7339 Spearman: 0.7315
2021-03-02 10:01:48 - Euclidean-Distance:       Pearson: 0.7392 Spearman: 0.7369
2021-03-02 10:01:48 - Dot-Product-Similarity:   Pearson: 0.7042 Spearman: 0.6861

```

**Comment by nreimers** [comment]
Not sure about PyTorch. But with older libraries (like Theano), BLAS made a big difference for the speed on floating point operations. Maybe you have a PyTorch binary that was compiled without external BLAS library?

It can be checked like this:
```
import torch 
print(*torch.__config__.show().split("\n"), sep="\n")
```
Output is then something like:

```
PyTorch built with:
...
- Build settings: BLAS=MKL
```

https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#build-options

MKL:
https://software.intel.com/content/www/us/en/develop/tools/math-kernel-library.html


Adding these libraries made quite a big difference for Theano / Tensorflow etc. (in the older days).

**Comment by cdpierse** [comment]
So here's the full output of mine. It looks like my build settings are identical and and MKL is confirmed to be enabled. Are there any major differences between my complete output and yours ? Possibly with GCC or something like that ?

```
PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 11.0.0
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, 
```

**Comment by nreimers** [comment]
Here the output from my server:
```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

Difference I see is the quite old GCC version (4.2 vs 7.3). Also your binary has USE_OPENMP=OFF. Open NMP also is a library that optimizes multi-process operations and shared memory. It can be quite important for the performance (at least for Theano it was important). But I don't know how PyTorch relies on it.

But in conclusion, I am not why the floating point operations are comparably slow on your machine.

**Comment by cdpierse** [comment]
I think you are right, it seems to be down to how Mac handles GCC. At least I know now, it doesn't seem very easy to overwrite Apple's version when running through Pytorch so I'm going to leave it. At least this is extra incentive for Mac users running locally to look into quantization. 

Gonna close this now, thanks for helping me out with this, appreciate it!

**Pull request closed without merging**
