### PR TITLE
[ENH] -- `CrossEncoder.rank`

### PR DESCRIPTION
**Pull request by it176131**
I found some spots in the :method:`CrossEncoder.rank` that could be updated to reflect best practices. Feel free to cherry-pick or reject.

Tested with Python 3.8 for minimum version coverage.

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hello!

I'm a bit hesitant to (already) add code with the `|=` operator, because Sentence Transformers is currently still supported on Python 3.8, whereas that operator is not. 
However, in about 1 month, [Python 3.8 will become deprecated](https://endoflife.date/python), and then I'll have no issues merging this PR.

- Tom Aarsen

**Comment by it176131** [comment]
> Hello!
> 
> I'm a bit hesitant to (already) add code with the `|=` operator, because Sentence Transformers is currently still supported on Python 3.8, whereas that operator is not. However, in about 1 month, [Python 3.8 will become deprecated](https://endoflife.date/python), and then I'll have no issues merging this PR.
> 
> * Tom Aarsen

Good catch! Interesting that the 3.8 tests didn't raise an exception 🤔

**Comment by tomaarsen** [comment]
Huh, you're right. Perhaps `rank` isn't under test, or I'm wrong and `|=` also works on Python 3.8.

**Comment by it176131** [comment]
> Huh, you're right. Perhaps `rank` isn't under test, or I'm wrong and `|=` also works on Python 3.8.

I'm not seeing a check in the [current test](https://github.com/UKPLab/sentence-transformers/blob/b6f114288f8cf1edc6eb7739d95b7adf15d49fcb/tests/test_cross_encoder.py#L136), but I'd be willing to add one for better coverage.

**Comment by tomaarsen** [comment]
That would be much appreciated!

**Comment by it176131** [comment]
> That would be much appreciated!

Updated the test!

**Comment by it176131** [comment]
@tomaarsen is there anything else we need before merging?

**Comment by tomaarsen** [comment]
I don't believe so! I think we're all set now, I hadn't merged it yet as I was wrapping up some work in another PR.
I plan to include this in the next release, which should be very soon (i.e. this week, I imagine).

- Tom Aarsen

**Pull request merged**
