### PR TITLE
Fall back to CPU device in case there are no PyTorch parameters

### LINKED ISSUE #2607: Models without PyTorch parameters don't work since v2.3.0
Hi, models that don't have any PyTorch parameters seem broken since sentence-transformers v2.3.0, e.g.

```python
from sentence_transformers import SentenceTransformer, models

st = SentenceTransformer(modules=[models.BoW(vocab=["a", "b", "c"])])
st.encode(["a"])
```

works as expected in v2.2.2 but crashes since v2.3.0 inside `self.device` because `next(...)` in the PyTorch 1.5 fallback branch raises `StopIteration`  (https://github.com/UKPLab/sentence-transformers/blob/v2.3-release/sentence_transformers/SentenceTransformer.py#L1122).

(More context: we sometimes use `SentenceTransformer` to wrap calls an embedding API so we can use them in the same way as local trainable models, now we have to add a dummy parameter such as `self.dummy = nn.Linear(1, 1)` to make it work)

I haven't tried the v3 branches yet, feel free to close in case this is fixed soon since it's only a small inconvenience. Thanks!

### PR DESCRIPTION
**Pull request by maxfriedrich**
Fixes #2607

### CODE REVIEW

**Comment by tomaarsen** [comment]
cc @michaelfeil your thoughts would be much appreciated, if you have the time!

Otherwise I'll merge this as-is, I think it looks very reasonable. Thanks for the PR!

- Tom Aarsen

**Comment by michaelfeil** [comment]
I think this behavior is a good idea.

nit  - I think you can also fallback without a `try:.. except: ..` as `next` provides a default.  https://docs.python.org/3/library/functions.html#next  `next(iterator, default)`

**Comment by maxfriedrich** [comment]
@michaelfeil The iterator doesn't return the device directly so we can't just write `next(gen, torch.device("cpu"))`, this is why I think it's nicer to keep the explicit `try: ... except: ...`, what do you think?

I only have the issue that models without any PyTorch parameters crash with `StopIteration` there, no other problems at the moment.

**Comment by tomaarsen** [comment]
I'm okay with the nested try-except, as I understand that the clean `next(iterator, default)` approach does not conveniently work here. Thanks for this PR! I think it'll become especially useful when I try to add ONNX support for Sentence Transformers.

- Tom Aarsen

**Pull request merged**
