### PR TITLE
Add `classifier_dropout` param for CrossEncoder.

### PR DESCRIPTION
**Pull request by PhilipMay**
This PR adds the option to set / change the `classifier_dropout` value. This way it is possible to set the dropout value of the classification head. This can be a very important hyperparameter for classification tasks (and also regression).

**This is a non breaking change:** When the `classifier_dropout` is `None` (the default) then nothing happens.

For more background please also see:
- https://github.com/huggingface/transformers/pull/12794
- https://github.com/huggingface/transformers/issues/12781
- https://github.com/huggingface/transformers/issues/12792

### CODE REVIEW

**Comment by PhilipMay** [comment]
One unrelated test fails: `FAILED tests/test_sentence_transformer.py::test_save_to_hub - TypeError: __init__() missing 1 required positional argument: 'pull_requests'`

**Comment by tomaarsen** [comment]
@PhilipMay I suspect that there's been a new release of `huggingface_hub` that changed the API for `GitRefs` that I use in one of the tests. I will look into this next week (as I'm off this week).

**Comment by PhilipMay** [comment]
> @PhilipMay I suspect that there's been a new release of `huggingface_hub` that changed the API for `GitRefs` that I use in one of the tests. I will look into this next week (as I'm off this week).

Many thanks @tomaarsen ! 🚀

**Comment by PhilipMay** [comment]
> @PhilipMay I suspect that there's been a new release of `huggingface_hub` that changed the API for `GitRefs` that I use in one of the tests. I will look into this next week (as I'm off this week).

Last release is from 20th Dec. 2023:

image

**Comment by PhilipMay** [comment]
I found the bug and reported it: https://github.com/huggingface/huggingface_hub/issues/1956

For this PR I applied a workaround.

**Comment by PhilipMay** [comment]
CI is green - can be merged from my point of view. :-)

**Comment by tomaarsen** [comment]
This looks great, thanks! And feel free to share any trained models with me, I'm curious to see what you'll cook up :)

**Pull request merged**
