### PR TITLE
Added methods _fit_save_checkpoint and _load_optimizer_schedule

### PR DESCRIPTION
**Pull request by petabyte**
#1086  This is to save the optimizer and scheduler during checkpoint and loading them again during fit if there is a saved state

### CODE REVIEW

**Comment by nreimers** [comment]
great, thanks for the PR, I was also looking forward to implement something like this. It might take some time to merge it, as I will be on vacation for the next two weeks.

**Comment by NhuanTDBK** [comment]
Great commits. Do you have any plan to merge this PR? This checkpoint with optimizer is necessary when we train models on SageMaker spot instance  @nreimers

**Comment by miguelwon** [comment]
Hi,
Any planes to merge the PR? It would be quite useful for many of us that have limited GPU hours.
Thanks

**Comment by tomaarsen** [comment]
Hello!

Since the v3.0 update, you can now resume training by passing `resume_from_checkpoint` on [`SentenceTransformerTrainer.train`](https://sbert.net/docs/package_reference/sentence_transformer/trainer.html#sentence_transformers.trainer.SentenceTransformerTrainer.train). This will load the full trainer state, including the optimizer.

- Tom Aarsen

**Pull request closed without merging**
