### PR TITLE
[`fix`] Add dtype cast for modules other than Transformer

### PR DESCRIPTION
**Pull request by ir2718**
The PR adds the `torch_dtype` cast for modules other than Transformer when loading the SentenceTransformer. (https://github.com/UKPLab/sentence-transformers/issues/2887)

### CODE REVIEW

**Comment by ahmedkooli** [comment]
Bug reference [link](https://github.com/UKPLab/sentence-transformers/issues/2887) :)

**Comment by ahmedkooli** [comment]
@ir2718 I'm seeing the PR not passing the [tests](https://github.com/UKPLab/sentence-transformers/actions/runs/10392749220/job/28778699837?pr=2889). I think you should change the code to:
```python
if model_kwargs is not None:
    if "torch_dtype" in model_kwargs:
        module = module.to(model_kwargs["torch_dtype"])
```

**Comment by ir2718** [comment]
@ahmedkooli 

Thanks, for some reason I thought an empty dict was the default.

**Comment by tomaarsen** [comment]
Heya @ir2718! 
Thanks for creating a PR here - I've adopted it with a bit of a different fix, as I noticed some edge cases didn't work:
* `{"torch_dtype": "auto"}`
* `{"torch_dtype": "float16"}`
* `{"torch_dtype": "bfloat16"}`

I've also added a test here. Ideally this should fix #2887

- Tom Aarsen

**Pull request merged**
