### PR TITLE
Add CachedGISTEmbedLoss

### PR DESCRIPTION
**Pull request by JacksonCakes**
As per discussed in #2583, this is the implementation of GradCache version of GISTEmbedLoss to reduce memory usage while maintaining performance levels comparable to those of GISTEmbedLoss.

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hello!

Thanks a bunch for this! I've been testing this alongside MNRL, CMNRL and normal GIST yesterday and today. It seems to roughly match their performance, though I'm using some simple training & testing data.
I'll assist with finishing up this PR today, which mostly involves making sure that CachedGISTEmbedLoss is mentioned in the documentation.

- Tom Aarsen

**Comment by JacksonCakes** [comment]
Hi! Sorry, I just realized that calculating similarity for the entire batch in the guide, instead of using mini-batches, also adds extra memory usage. That's not ideal since I can handle up to a batch size of 4096 with CMNR loss, but only 1024 for this. I've made some adjustments to the guided part to address this.

**Comment by tomaarsen** [comment]
I think there's a small issue with 3208e611247f920ffa18262e1d1839a8f85af340, the loss is always 0 it seems. These are some of my logs: 
image

(Green is 3208e611247f920ffa18262e1d1839a8f85af340, Salmon is 5c054da665ec0e82d834f37edbb1767eb11ef093)

Additionally, the memory usage is actually a tad higher:
image

But that might also be somehow related to the 0 loss.

- Tom Aarsen

**Comment by JacksonCakes** [comment]
Ah my bad, i think it's because I did not properly offset the diagonal part resulting in the guide mask always select diagonally from the first element, which easily causing -inf in the scores and potentially leading to weird loss.

**Comment by tomaarsen** [comment]
After further experimentation, I can confirm that 3215c06 matches the performance (losses, evaluations) of 5c054da665ec0e82d834f37edbb1767eb11ef093 exactly, but the former allows for much higher batch sizes. E.g. I was able to set my batch size to an absurd 50k.

Great job!

I'll work on the documentation things that I had mentioned.

- Tom Aarsen

**Comment by JacksonCakes** [comment]
Good to know! Thank you for your effort! Happy to help :)

**Comment by tomaarsen** [comment]
I think this is ready! I'll merge it now, so it can be included in tomorrow/Thursday's release. Do feel free to let me know if there were things that you think are missing/suboptimal.

Thanks for your time/work on this!

cc @avsolatorio, @kwang2049

- Tom Aarsen

**Pull request merged**
